task: det
model: vit
data_dir: /home3/dnrx52/SCOPE/datasets/coco
bs: 4
pretrained: ./checkpoint/pretrained/vit_cls_size224_patch16_dim384_depth12_best.pth  # 72.81%
img_scale: [1333, 800]
size: 224
patch: 16
dim: 384
depth: 12
heads: 6
mlp_dim: 1536
dim_head: 64

n_epochs: 12  # 1x schedule
lr: 2.5e-5  # 1e-4 * (bs/16) with bs=4
min_lr: 0.000001
warmup_iters: 1000
weight_decay: 0.05
opt: adamw
betas: [0.9, 0.999]
amp: true
nowandb: false
