task: seg
model: vitcope
data_dir: ./datasets/ADE20K/ADEChallengeData2016
bs: 16
pretrained: ./checkpoint/pretrained/COPE/vitcope_cls_size224_patch16_dim384_depth12_best.pth
size: 224
patch: 16
dim: 384
depth: 12
heads: 6
mlp_dim: 1536
dim_head: 64
n_epochs: 32
lr: 6e-5
min_lr: 0
warmup_epochs: 0.9
weight_decay: 0.01
opt: adamw
amp: true
nowandb: false
