task: cls
model: vit
dataset: imagenet
data_dir: /home3/dnrx52/vitcope
bs: 256
size: 224
n_epochs: 300
patch: 16
dim: 1024
depth: 24
heads: 16
mlp_dim: 4096
lr: 2.5e-4  # 1e-3 * (bs/1024) with bs=256
min_lr: 0
warmup_epochs: 0
weight_decay: 0.05
betas: [0.9, 0.999]
lrschedule: one_cycle_cosine
opt: adamw
amp: true
aug: true
mixup: true
cutmix: true
random_erasing: true
repeated_augmentations: true
label_smoothing: true
stochastic_depth: true
nowandb: false
