task: cls
model: vitcope
dataset: cifar10
data_dir: ./data
bs: 128
size: 32
n_epochs: 100
patch: 4
dim: 192
depth: 12
heads: 3
mlp_dim: 768
dim_head: 64
use_cls_token: false
pool: mean
lr: 1e-4
min_lr: 1e-6
warmup_epochs: 5
opt: adamw
amp: true
aug: true
mixup: true
cutmix: true
random_erasing: true
repeated_augmentations: true
label_smoothing: true
stochastic_depth: true
drop_path_rate: 0.1
nowandb: false

weight_decay: 0.05
betas: [0.9, 0.999]
lrschedule: one_cycle_cosine
