# configs/vitcpe_imagenet100_tiny.yaml - ViT-CPE Tiny on ImageNet-100
task: cls
model: vitcpe
dataset: imagenet100
data_dir: /home3/dnrx52/vitcope/vitcifar/new-imagenet100-folder

bs: 128
size: 256
n_epochs: 150
patch: 32

dim: 384
depth: 12
heads: 6
mlp_dim: 1536
dim_head: 64

lr: 1e-4
min_lr: 0
warmup_epochs: 0
opt: adam
amp: true
aug: true
nowandb: false
