task: cls
model: vitcope
dataset: imagenet
data_dir: /tmp/vitcope
bs: 768
size: 224
n_epochs: 300
patch: 16
dim: 384
depth: 12
heads: 6
mlp_dim: 1536
dim_head: 64
use_cls_token: false
pool: mean
lr: 7.5e-4  # 1e-3 * (bs/1024) with bs=768
min_lr: 0
warmup_epochs: 5
weight_decay: 0.05
betas: [0.9, 0.999]
lrschedule: one_cycle_cosine
opt: adamw
amp: true
aug: true
mixup: true
cutmix: true
random_erasing: true
repeated_augmentations: true
label_smoothing: true
stochastic_depth: true
drop_path_rate: 0.1
nowandb: false
