task: cls
model: vitscope_nocls
dataset: imagenet100
data_dir: /home3/dnrx52/vitcope/vitcifar/imagenet100
bs: 256
size: 224
n_epochs: 100
patch: 16
dim: 192
depth: 12
heads: 3
mlp_dim: 768
dim_head: 64
use_cls_token: true
pool: cls
lr: 3e-4
min_lr: 1e-5
warmup_epochs: 2
opt: adamw
amp: true
aug: true
mixup: true
cutmix: true
random_erasing: true
repeated_augmentations: true
label_smoothing: true
stochastic_depth: true
drop_path_rate: 0.1
nowandb: false
weight_decay: 0.05
betas: [0.9, 0.999]
lrschedule: one_cycle_cosine
